version: "3"  

services:
  web:
    build: node
    container_name: web
    volumes:
      - ./node:/usr/src/app
    ports: 
      - 3000:3000
    depends_on:
      - db

  db: 
    build: mysql
    container_name: mysql-db
    restart: always
    volumes: 
      - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    
