version: "3"  

services:
  web:
    image: node:16.5.0-alpine
    container_name: web
    working_dir: /usr/src/app
    volumes:
      - ./node:/usr/src/app
    ports: 
      - 3000:3000
    command: tail -f /dev/null
