version: "3"  

services:
  web:
    build: node
    container_name: web
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db
    ports:
      - 3000

  db: 
    build: mysql
    container_name: mysql-db
    restart: always
    volumes: 
      - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  proxy:
    image: nginx:1.21.1-alpine
    container_name: proxy-nginx
    restart: always
    ports: 
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - web
    
